"use client";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import { Book } from "lucide-react";
import { useUserStore } from "@/store/store";
import { Toaster } from "react-hot-toast";
import { useEffect, useState } from "react";
import { onAuthStateChanged, getAuth } from "firebase/auth";
import {app} from "@/firebase"; // Assuming your firebase config file is here

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const currentYear = new Date().getFullYear();

export default function RootLayout({ children }) {
  const { isLoggedIn, login, logout } = useUserStore(state => state);
  const [isUser,setUserLog] = useState(null);
  
  // Use useEffect to check for auth state changes
  useEffect(() => {
    const auth = getAuth(app);
    const unsubscribe = onAuthStateChanged(auth, (user) => {
      if (user) {
        // User is signed in
        setUserLog(user)
      }
    });

    // Cleanup the subscription on component unmount
    return () => unsubscribe();
  }, [login, logout]); // The effect depends on login and logout from the store

  return (
    <html lang="en">
      <head>
        <title>Resource Sharing Hub</title>
        <meta name="description" content="Generated by create next app" />
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-primary`}
      >
        <Toaster position="top-center" reverseOrder={false} toastOptions={{
          className: '',
          duration: 3000,
          removeDelay: 1000
        }} />
        <header className="py-6 bg-secondary">
          <nav className="flex md:justify-between md:items-center px-4 mx-auto max-w-7xl">
            <Link href='/' className="font-bold text-2xl primary-text duration-300">
              Resource Hub
            </Link>

            <ul className="hidden md:flex gap-8 items-center justify-center">
              <li className="px-4 py-2 rounded-2xl hover:bg-[#3730A3] hover:text-white">
                <Link href='/about' className="p-3 hover:rounded-full primary-text md:text-lg lg:text-xl font-semibold cursor-pointer duration-300">
                  About
                </Link>
              </li>
              <li className="px-4 py-2 rounded-2xl hover:bg-[#3730A3] hover:text-white"> 
                <Link href='/resources' className="primary-text md:text-lg lg:text-xl font-semibold cursor-pointer duration-300">
                  Resources
                </Link>
              </li>
              <li className="px-4 py-2 rounded-2xl hover:bg-[#3730A3] hover:text-white">
                <Link href='/upload-resources' className="primary-text md:text-lg lg:text-xl font-semibold cursor-pointer duration-300">
                  Upload Document
                </Link>
              </li>
              <li className="px-4 py-2 rounded-2xl hover:bg-[#3730A3] hover:text-white">
                {!isUser ? (
                  <Link href='/login' className="primary-text md:text-lg lg:text-xl font-semibold cursor-pointer duration-300">
                    Login
                  </Link>
                ) : (
                  <Link href='/profile' className="primary-text md:text-lg lg:text-xl font-semibold cursor-pointer duration-300">
                    Profile
                  </Link>
                )}
              </li>
            </ul>
          </nav>
        </header>
        
        {children}

        <footer className="bg-primary primary-text py-10 px-4 shadow-xl shadow-black">
          <div className="container mx-auto flex flex-col items-center text-center space-y-8">
            <div className="flex flex-col items-center space-y-2">
              <a href="/" className="flex items-center space-x-2">
                <Book className="text-accent" size={28} />
                <span className="text-2xl font-bold tracking-tight primary-text">StudyHub</span>
              </a>
              <p className="text-sm max-w-md secondary-text">
                Connecting students with shared knowledge to help you succeed.
              </p>
            </div>

            <div className="flex flex-wrap justify-center gap-x-6 gap-y-2 text-sm font-medium">
              {["Browse Resources", "Upload Work", "About Us", "Contact", "Privacy Policy", "Terms of Service"].map((item, index) => (
                <a 
                  key={index} 
                  href={`/${item.toLowerCase().replace(/\s+/g, '-')}`}
                  className="primary-text transition-colors duration-200"
                >
                  {item}
                </a>
              ))}
            </div>

            <div className="pt-6 border-t border-primary w-full max-w-xl">
              <p className="text-xs secondary-text">
                &copy; {currentYear} StudyHub. All rights reserved.
              </p>
            </div>
          </div>
        </footer>
      </body>
    </html>
  );
}